# RETROSPECTIVE ANALYSIS
## I approached this analysis by attempting to find a correlation between High Temp and number of people crossing the Brooklyn bridge. What I found was that there is a positive relationship between HIGHER TEMPS and more people crossing the Brooklyn bridge on bikes. This is most likely due to the fact that people want to ride their bikes more when the weather is nice outside, not too cold. 

## Only using High temp and not Low temp could potentially be a risk when trying to predict how many people will cross the Brooklyn bridge. If the High is a 66(°F), but the actual temp of that day is closer to the Low of 44(°F), my model would probably predict more people would cross the bridge on bike than the actual amount.

## What I should done is look at how the Low temp correlates to how many people cross the brooklyn bridge, as well as factors such as Precipitation. Using these three factors, one might be able to predict how many people cross the Brooklyn Bridge on bike more accuratly on a based off of what the weather is looking like on a specific day.

In [1]:
# Dependencies
import pandas as pd
import statsmodels.api as sm
import plotly.express as plt
import os

In [2]:
bikecounts_file = os.path.join('../','Resources', 'bikecounts.csv')
bikecounts_df = pd.read_csv(bikecounts_file)
bikecounts_df['Day'] = pd.to_datetime(bikecounts_df['Day'])
bikecounts_df.head()

,Unnamed: 0,Date,Day,High Temp (°F),Low Temp (°F),Precipitation,Brooklyn Bridge,Manhattan Bridge,Williamsburg Bridge,Queensboro Bridge,Total
0,0,2016-04-01,2016-04-01,78.1,66.0,0.01,1704.0,3126,4115.0,2552.0,11497
1,1,2016-04-02,2016-04-02,55.0,48.9,0.15,827.0,1646,2565.0,1884.0,6922
2,2,2016-04-03,2016-04-03,39.9,34.0,0.09,526.0,1232,1695.0,1306.0,4759
3,3,2016-04-04,2016-04-04,44.1,33.1,0.47 (S),521.0,1067,1440.0,1307.0,4335
4,4,2016-04-05,2016-04-05,42.1,26.1,0,1416.0,2617,3081.0,2357.0,9471

In [3]:
# Hypothesis: Higher Temp has a relationship with how many people cross Brooklyn Bridge per day
# Null Hypothesis: High Temp has no association with how many people cross Brooklyn Bridge on bike
# Alternative Hypothesis: High Temp correlates with how many people cross Brooklyn Bridge on bike
bikecounts_df.corr()
X = bikecounts_df[['High Temp (°F)','Low Temp (°F)']]
y = bikecounts_df['Brooklyn Bridge']
X = sm.add_constant(X)
model = sm.OLS(y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        Brooklyn Bridge   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.583
Method:                 Least Squares   F-statistic:                     21.27
Date:                Tue, 02 Nov 2021   Prob (F-statistic):           2.84e-06
Time:                        12:55:59   Log-Likelihood:                -234.97
No. Observations:                  30   AIC:                             475.9
Df Residuals:                      27   BIC:                             480.1
Df Model:                           2
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const          -1478.9205    653.710     -2.262      0.032   -2820.222    -137.619
High Temp (°F)    97.4074     18.563      5.247      0.000      59.319     135.496
Low Temp (°F)    -46.3743     21.800     -2.127      0.043     -91.104      -1.645
==============================================================================
Omnibus:                        0.974   Durbin-Watson:                   1.306
Prob(Omnibus):                  0.615   Jarque-Bera (JB):                0.809
Skew:                          -0.047   Prob(JB):                        0.667
Kurtosis:                       2.201   Cond. No.                         432.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [4]:
# With our p value from the summary, we can reject the null hypothesis, meaning that there is a positive 
# relationship between HIGHER TEMPS and more people crossing the Brooklyn Bridge on bikes